### ISSUE TITLE
调用后直接崩溃了

### ISSUE THREAD

**Issue by zanezhangzz** [leanflutter/flutter_tencent_captcha#11]
```
➜  ~ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.19.6, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2024.1.2)
[✓] IntelliJ IDEA Community Edition (version 2024.1.2)
[✓] VS Code (version 1.89.1)
[✓] VS Code (version 1.90.0-insider)
[✓] Connected device (5 available)
[✓] Network resources
```

```
import 'package:flutter/material.dart';
import 'package:flutter_tencent_captcha/flutter_tencent_captcha.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  const MyHomePage({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('test'),
      ),
      body: Column(
        children: [
          ElevatedButton(
            onPressed: () async {
              await TencentCaptcha.verify(
                  config: TencentCaptchaConfig(
                appId: 'hide',
                bizState: 'tencent-captcha',
                enableDarkMode: true,
              ));
            },
            child: Text('test'),
          ),
        ],
      ),
    );
  }
}

```

```
Launching lib/main.dart on MI 9 in debug mode...
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
Connecting to VM Service at ws://127.0.0.1:65534/E-FYVLYgyXQ=/ws
I/tencent_captch(28164): ProcessProfilingInfo new_methods=1181 is saved saved_to_disk=1 resolve_classes_delay=8000
I/Timeline(28164): Timeline: Activity_launch_request time:17985225813
D/ViewContentFactory(28164): initViewContentFetcherClass
I/ContentCatcher(28164): ViewContentFetcher : ViewContentFetcher
D/ViewContentFactory(28164): createInterceptor took 0ms
I/WebViewFactory(28164): Loading com.google.android.webview version 83.0.4103.106 (code 410410683)
I/cr_LibraryLoader(28164): Loaded native library version number "83.0.4103.106"
I/cr_CachingUmaRecorder(28164): Flushed 3 samples from 3 histograms.
I/TetheringManager(28164): registerTetheringEventCallback:com.example.demo_flutter_tencent_captcha
W/chromium(28164): [WARNING:dns_config_service_posix.cc(341)] Failed to read DnsConfig.
D/EgretLoader(28164): EgretLoader(Context context)
D/EgretLoader(28164): The context is not activity
W/tencent_captch(28164): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
W/cr_media(28164): Requires BLUETOOTH permission
D/DecorView[](28164): getWindowModeFromSystem  windowmode is 1
D/DecorView(28164): createDecorCaptionView windowingMode:1 mWindowMode 1 isFullscreen: true
W/VideoCapabilities(28164): Unsupported mime image/vnd.android.heic
W/VideoCapabilities(28164): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(28164): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(28164): Unsupported mime video/x-ms-wmv
D/AndroidRuntime(28164): Shutting down VM
E/AndroidRuntime(28164): FATAL EXCEPTION: main
E/AndroidRuntime(28164): Process: com.example.demo_flutter_tencent_captcha, PID: 28164
E/AndroidRuntime(28164): java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.EventChannel$EventSink.success(java.lang.Object)' on a null object reference
E/AndroidRuntime(28164): 	at org.leanflutter.plugins.flutter_tencent_captcha.FlutterTencentCaptchaPlugin$1.onLoaded(FlutterTencentCaptchaPlugin.java:161)
E/AndroidRuntime(28164): 	at org.leanflutter.plugins.flutter_tencent_captcha.TencentCaptchaSender.onLoaded(TencentCaptchaSender.java:18)
E/AndroidRuntime(28164): 	at org.leanflutter.plugins.flutter_tencent_captcha.TencentCaptchaJsInterface$1.run(TencentCaptchaActivity.java:40)
E/AndroidRuntime(28164): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(28164): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(28164): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(28164): 	at android.app.ActivityThread.main(ActivityThread.java:8060)
E/AndroidRuntime(28164): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28164): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
E/AndroidRuntime(28164): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
I/Process (28164): Sending signal. PID: 28164 SIG: 9
Lost connection to device.

Exited.
```

**Comment by zanezhangzz** [comment]
忘记 init 了，😅
